language: python
python:
  - "2.7"
# command to install dependencies
addons:
  postgresql: "9.3"

install: "pip install -r requirements.txt"
# command to run tests

before_script:
  - psql -c 'create database dr_quiz_db;' -U postgres
  - psql -c 'create user dr_quiz_db;' -U postgres
  - psql -c 'grant all privileges on database dr_quiz_db to dr_quiz_db;' -U postgres
  - python run.py db upgrade

script: python tests.py