"""empty message

Revision ID: 527a11ac7945
Revises: None
Create Date: 2015-06-24 20:35:51.193598

"""

# revision identifiers, used by Alembic.
revision = '527a11ac7945'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question', sa.String(length=1000), nullable=False),
                    sa.Column('real_id', sa.Integer(), nullable=False),
                    sa.Column('signed', sa.Boolean(), nullable=True),
                    sa.Column('sign_name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('real_id')
                    )
    op.create_table('answer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('answer', sa.String(length=1000), nullable=False),
                    sa.Column('is_correct_answer', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['question_id'], ['question.id'], )
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    ### end Alembic commands ###
